<?php

namespace Workshop5Bundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * telephone_numberRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class telephone_numberRepository extends EntityRepository
{
}
