<?php

namespace Workshop5Bundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UsersGroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsersGroupRepository extends EntityRepository
{
}
